### PR TITLE
Extension System

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
This is a very large PR. It contains a comprehensive extension system that allows users to do everything described in this document: https://github.com/aquifer/aquifer/wiki/Adding,-removing,-loading,-and-listing-extensions
## NOTE

This should NOT be reviewed or merged before #14.
## Steps to test
- Checkout this branch.
- Run `npm install && npm link` within the aquifer repository.
- Checkout [this](https://github.com/aquifer/aquifer-drush) git repository in another folder.
- Create an aquifer project in any directory (not within this repo): `aquifer create myDir`
- Change your pwd into the directory aquifer should have created: `cd myDir`.
- Run `aquifer extension-add aquifer-drush -s /path/to/aquifer-drush`
- Ensure that aquifer returns with a success message about installing aquifer-drush.
- Run `aquifer extension-remove aquifer-drush`
- Ensure that aquifer returns a success message about removing aquifer-drush.
- Run `aquifer extension-add aquifer-drush -s git+ssh://git@github.com/aquifer/aquifer-drush` (re-install the module via github repo)
- Within your aquifer project dir, run `rm -r .aquifer/node_modules`
- Run `aquifer`
- Ensure that aquifer notifies you of the fact that your installed extensions are not downloaded.
- As the prompt should instruct, run `aquifer extensions-load`
- Within your aquifer project dir, run `ls .aquifer/node_modules`, and ensure that `aquifer-drush` is indeed loaded.
- Run `aquifer build`.
- Run `aquifer drush status`, and ensure that it returns valid information about an uninstalled Drupal site (the one you just built).
## Extension CLI help:

screen shot 2015-06-28 at 5 50 24 pm
## Extension installation:

screen shot 2015-06-28 at 10 30 55 pm
## Extension uninstallation:

screen shot 2015-06-28 at 10 30 37 pm
## Extensions out of sync, and being reloaded:

screen shot 2015-06-28 at 10 31 43 pm

### CODE REVIEW

**Comment by fluxsauce** [comment]
```
npm WARN package.json path@0.11.14 path is also the name of a node core module.
```

**Comment by fluxsauce** [comment]
`aquifer extensions-load` gives redundant error message.

screen shot 2015-07-09 at 12 59 44 pm

**Comment by fluxsauce** [comment]
Odd race condition?

screen shot 2015-07-09 at 1 00 40 pm

**Comment by fluxsauce** [comment]
> Run `aquifer deploy-vagrant`, and ensure that it returns `pizza`.

Uh, nothing happened.

screen shot 2015-07-09 at 1 03 08 pm

**Comment by patrickocoffeyo** [comment]
@fluxsauce Thank you for the review. I'll address these issues as soon as possible.

**Comment by patrickocoffeyo** [comment]
I had neglected to push commits to the `aquifer-vagrant` repo :cry: It's back up. I'll finish responding to these and then re-submit for review.

**Comment by chasingmaxwell** [comment]
@fluxsauce @patrickocoffeyo I think my last commit should fix the issue of the command not doing anything. However, I'm not seeing where aquifer-vagrant returns pizza anyway.

Previously the command wasn't even being parsed and added to the list of available commands when running `aquifer`. Now it does.

**Comment by chasingmaxwell** [comment]
Updated the steps to demo to reflect the new `npm link` workflow for local extensions.

**Comment by chasingmaxwell** [comment]
@patrickocoffeyo if you install a local extension with `/path/to/extension` then remove it with `/path/to/extension/` (with the trailing slash) it removes the node module but does not remove the entry from aquifer.json which causes an error:

selection_081

**Comment by chasingmaxwell** [comment]
My last few commits fixed that last issue. The only issue that remains is the one @fluxsauce pointed out about the redundant error message. Unfortunately, It's not very easy to get rid of since when you run extensions-load initially there is still a broken extension which generates that message. After the extension is loaded, on the next command, the message goes away. I'm fine with merging this PR with that issue unresolved. We could create an issue and revisit later.

**Comment by chasingmaxwell** [comment]
@patrickocoffeyo if you're satisfied with where this landed you can :shipit:

**Comment by patrickocoffeyo** [comment]
screen shot 2015-08-24 at 18 34 43

**Comment by patrickocoffeyo** [comment]
@JeffTomlinson After some work on aquifer-drush and the extensions api, this is ready to re-review.

**Pull request merged**
