### PR TITLE
Allow override of core .htaccess and robots.txt

### PR DESCRIPTION
**Pull request by JeffTomlinson**
Adds a "root" directory to the project. The files within this directory will overwrite those in the drupal root in the build.

### CODE REVIEW

**Comment by patrickocoffeyo** [comment]
This is a great idea. I'm testing now!

**Comment by patrickocoffeyo** [comment]
:shipit: !

**Comment by JeffTomlinson** [comment]
@patrickocoffeyo: Merged in your build directory structure changes and set the root files source directory to "root". Ready for re-review.

**Comment by patrickocoffeyo** [comment]
@JeffTomlinson ship it!!!!!!

**Pull request merged**
