### PR TITLE
Test setup and initial functional/unit tests

### PR DESCRIPTION
**Pull request by infiniteluke**
# #111: Setup initial tests
## Test (get it? lololol)
- Check out `111-add-mocha`
- `npm i`
- `npm test` should run 2 passing functional and unit tests
- `npm run test-unit` should 1 passing unit test
- `npm run test-functional` should 1 passing functional test

### CODE REVIEW

**Comment by patrickocoffeyo** [comment]
@infiniteluke this looks _awesome_!!! Would it be possible for you to make this PR against the 1.0.0 branch? We are sprinting in that branch.

**Comment by patrickocoffeyo** [comment]
If that's too much work, shipit and we'll merge it upstream into 1.0.0

**Comment by infiniteluke** [comment]
Was going to re-roll this but there was a nasty merge conflict in the build api that I didn't want to try to resolve myself. Sooo... :shipit:

**Comment by infiniteluke** [comment]
`dev` will need to be merged into `1.0.0` now

**Pull request merged**
