### PR TITLE
Documentation, prep for first release

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
This PR brings proper documentation to the README.md file, and preps the project for release.

### CODE REVIEW

**Comment by chasingmaxwell** [comment]
This ordered list isn't being output correctly. I assume you want each of those on a new line.
selection_085

**Comment by patrickocoffeyo** [comment]
@chasingmaxwell thanks! Fixed

**Comment by chasingmaxwell** [comment]
Looks great to me! You probably want more eyes on it but I give it a :+1:

**Comment by JeffTomlinson** [comment]
LGTM :shipit:

**Pull request merged**
