### PR TITLE
(node:30413) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

### LINKED ISSUE #132: graceful-fs
> (node:27163) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

I'm trying to use aquifer for a project, but I can't seem to get a working install. I get an error on install, and some version of the message above any time I attempt to use it. I've attempted to update graceful-fs without any difference. 
I'm using a new Macbook if it makes a difference.

### PR DESCRIPTION
**Pull request by proofoftom**
Fixes #132 by updating fs-extra to v0.30.0.

### CODE REVIEW

**Comment by patrickocoffeyo** [comment]
@tommycox Awesome, thanks for this :) Can you please provide some "steps to test"? Apologies, we haven't added a CONTRIBUTION.md file yet specifying workflow around creating PRs, but it's helpful if the steps to functionally test a change are explicitly defined. (See an example: https://github.com/aquifer/aquifer/pull/133)

**Comment by proofoftom** [comment]
Sure! This one is pretty straight forward.

**To Test:**
When running any aquifer command the following warning is displayed:

``` shellsession
$ aquifer
(node:67000) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

After applying the pull request the graceful-fs module is updated with the fs-extras module and thus removes the warning.

**Comment by patrickocoffeyo** [comment]
@tommycox Excellent, I'll functionally review :)

**Comment by patrickocoffeyo** [comment]
@tommycox This is a :shipit: :) Thank you!

**Pull request merged**
