### PR TITLE
Merge dev into 1.0.0

### PR DESCRIPTION
**Pull request by ccjjmartin**
## Purpose:
- Merge dev into 1.0.0
## Notes:
- This PR is to summarize the difference between the branches.
- Cannot merge due to conflicts

### CODE REVIEW

**Comment by patrickocoffeyo** [comment]
@ccjjmartin Lemme take a look at this conflict.

**Comment by patrickocoffeyo** [comment]
@ccjjmartin Ah ok, so the dev branch is old and stale and should be deleted. Nothing in the code is actually worth anything, however the change to the README is good. I'll make a PR with that change to the readme, and then close this PR. does that sound ok?

**Comment by patrickocoffeyo** [comment]
Ah, we also want to keep the gitignore updates. Let me actually resolve this conflict in another branch, and then propose a merge in a PR.

**Comment by ccjjmartin** [comment]
Sounds good

**Pull request closed without merging**
