### PR TITLE
Arrays in aquifler.local.json should overwrite those in aquifer.json

### PR DESCRIPTION
**Pull request by chasingmaxwell**
We should put some substantial testing into this to make sure this doesn't cause issues with some other config property defined in aquifer.local.json. In my testing so far it behaves as it should.

You can test this with the following method:
- [ ] Add this to your aquifer.json:
  
  ``` json
  "run": {
    "scripts": {
      "hello": [
        "echo 1",
        "echo 2",
        "echo 3",
        "echo 4",
        "echo 5"
      ]
    }
  }
  ```
- [ ] Add this to your aquifer.local.json:
  
  ``` json
  "run": {
    "scripts": {
        "hello": [
          "echo A",
          "echo B",
          "echo C"
        ]
      }
  }
  ```
- [ ] Run `aquifer run hello`
- [ ] See the output is:
  
  ```
  A
  B
  C
  ```
- [ ] Try out a number of other config overrides in aquifer.local.json and make sure they all do what you expect.

### CODE REVIEW

**Comment by generalredneck** [comment]
You got my vote for a merge as I tried it on a new build with the example you and I both used. Might see if @JeffTomlinson will hit up his nursing project with it and see if it works.

**Comment by JeffTomlinson** [comment]
@chasingmaxwell This is breaking on `preSync` and `postBuild` commands that get run during `aquifer build`.

In `aquifer.json`:

```
"run": {
  "scripts": {
    "hello": [
      "echo 1",
      "echo 2",
      "echo 3",
      "echo 4",
      "echo 5"
    ]
  },
  "preSync": [
    "echo pizza",
    "echo beer"
  ],
  "postBuild": [
    "echo foo",
    "echo bar"
  ]
}
```

aquifer_local_json_-_aquifer-d8_-____sites_aquifer-d8_

**Comment by chasingmaxwell** [comment]
@JeffTomlinson My last commit should address the issue you found.

**Comment by JeffTomlinson** [comment]
Works. W0000t! :shipit:

**Pull request merged**
